# Generated by Django 4.0.5 on 2022-07-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listings_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='amount_bought',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='bulk_price',
            field=models.BooleanField(null=True),
        ),
    ]
