# Generated by Django 4.0.5 on 2022-07-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listings_contributors_alter_listings_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bulk_price',
            field=models.IntegerField(null=True),
        ),
    ]
