# Generated by Django 4.0.5 on 2022-07-13 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0007_remove_listings_contributors_listings_contributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='ingredient',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='user_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
